model:
  vp_path: '/disk/student/dvoytan/Devito/HESS_VTI/numpy/'
  vs_path: '/disk/student/dvoytan/Devito/HESS_VTI/numpy/'
  rho_path: '/disk/student/dvoytan/Devito/HESS_VTI/numpy/'
  spacing: [20.0, 20.0] #dx, dz (m)
  shape: [500, 174] #nx, nz. if None, inferred from vp
  #Boundary Conditions
  nbl: 30
  bcs: 'damp' #type of boundary condition
  fs: false #Free surface boundary condition if true
solver:
  #Time axis. 
  tn: 6.0 #units of seconds
  cfl: None #If provided overrides the devito Courant–Friedrichs–Lewy condition value.
  resample_dt: 0.002 #resamples synthetics to the provided dt
  #Kernel
  kernel: 'centered'
  space_order: 4
  time_order: 2
  dtype: 'float32'
  autotune: false
source:
  #For now only a Ricker wavelet is supported with median frequency f_0
  f0: 8 #Hz
acquisition:
  src_x: 800 #m
  src_z: 40 #m
  rcv_x: [0, 500, 1] #start, stop stride in index
  rcv_z: 80 #m
output:
  outdir: './OUTPUT/'
  file_prefix: 'shot'
  autotune: 'off'
  # save_rec_locs: true #Each gather will save a key 'rec' saving the absolute rec locations
  # save_src_locs: true #Each gather will save a key 'src' saving the absolute source locations
distributed:
  use_mpi: false #Domain decomposition of the solver and serial over shots. Good for 
  n_workers: 10